-- Restore MVP schema (single-user cloud sync)
-- Sleep rows: identity is (user_id, sleep_date).
create table if not exists public.sleep_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001',
  sleep_date date not null,
  bed text not null,
  sleep_start text not null,
  sleep_end text not null,
  bathroom text[] not null default '{}',
  alarm text[] not null default '{}',
  nap_start text,
  nap_end text,
  waso integer not null default 0 check (waso >= 0),
  labels text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sleep_days_user_id_sleep_date_key unique (user_id, sleep_date)
);

create table if not exists public.sleep_day_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001',
  sleep_date date not null,
  bed text,
  sleep_start text,
  sleep_end text,
  bathroom text[] not null default '{}',
  alarm text[] not null default '{}',
  nap_start text,
  nap_end text,
  waso integer not null default 0 check (waso >= 0),
  labels text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sleep_day_drafts_user_id_sleep_date_key unique (user_id, sleep_date)
);

create table if not exists public.user_settings (
  user_id uuid primary key,
  language text not null default 'en' check (language in ('en', 'ja')),
  theme_override text check (theme_override in ('day', 'night')),
  clock_format text not null default '24h' check (clock_format in ('12h', '24h')),
  quality_palette text not null default 'auto' check (quality_palette in ('meadow', 'harbor', 'auto')),
  remaining_wake_open_min integer not null default 35 check (remaining_wake_open_min >= 0 and remaining_wake_open_min <= 100),
  remaining_wake_winding_min integer not null default 15 check (remaining_wake_winding_min >= 0 and remaining_wake_winding_min <= 100),
  remaining_wake_phase_heads_up_mins integer not null default 30 check (remaining_wake_phase_heads_up_mins in (0, 15, 30, 45, 60)),
  tonight_target_sleep_min integer,
  tonight_target_wake_min integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (remaining_wake_open_min > remaining_wake_winding_min)
);

-- PostgREST: allow MVP anon sync (same pattern as other public tables; tighten with RLS when auth lands)
grant select, insert, update on public.user_settings to anon, authenticated;

create or replace function public.set_sleep_days_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_sleep_days_updated_at on public.sleep_days;
create trigger trg_sleep_days_updated_at
before update on public.sleep_days
for each row execute function public.set_sleep_days_updated_at();

drop trigger if exists trg_sleep_day_drafts_updated_at on public.sleep_day_drafts;
create trigger trg_sleep_day_drafts_updated_at
before update on public.sleep_day_drafts
for each row execute function public.set_sleep_days_updated_at();

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_sleep_days_updated_at();

insert into public.user_settings (
  user_id,
  language,
  theme_override,
  clock_format,
  quality_palette,
  remaining_wake_open_min,
  remaining_wake_winding_min,
  remaining_wake_phase_heads_up_mins,
  tonight_target_sleep_min,
  tonight_target_wake_min
)
values (
  '00000000-0000-0000-0000-000000000001',
  'en',
  null,
  '24h',
  'auto',
  35,
  15,
  30,
  null,
  null
)
on conflict (user_id) do update
set
  language = excluded.language,
  theme_override = excluded.theme_override,
  clock_format = excluded.clock_format,
  quality_palette = excluded.quality_palette,
  remaining_wake_open_min = excluded.remaining_wake_open_min,
  remaining_wake_winding_min = excluded.remaining_wake_winding_min,
  remaining_wake_phase_heads_up_mins = excluded.remaining_wake_phase_heads_up_mins;

create or replace function public.promote_draft_if_complete(
  p_user_id uuid,
  p_sleep_date date,
  p_patch jsonb
)
returns table (promoted boolean, result_sleep_date date) as $$
declare
  v_patch jsonb := coalesce(p_patch, '{}'::jsonb);
  v_user_id uuid := coalesce(
    p_user_id,
    '00000000-0000-0000-0000-000000000001'::uuid
  );
  v_sleep_date date;
  v_draft public.sleep_day_drafts%rowtype;
  v_complete boolean := false;
begin
  if p_sleep_date is null then
    raise exception 'p_sleep_date is required';
  end if;

  v_sleep_date := p_sleep_date;

  insert into public.sleep_day_drafts (user_id, sleep_date)
  values (v_user_id, v_sleep_date)
  on conflict on constraint sleep_day_drafts_user_id_sleep_date_key do nothing;

  update public.sleep_day_drafts as d
  set
    bed = case
      when v_patch ? 'bed' then nullif(trim(v_patch->>'bed'), '')
      else bed
    end,
    sleep_start = case
      when v_patch ? 'sleep_start' then nullif(trim(v_patch->>'sleep_start'), '')
      else sleep_start
    end,
    sleep_end = case
      when v_patch ? 'sleep_end' then nullif(trim(v_patch->>'sleep_end'), '')
      else sleep_end
    end,
    bathroom = case
      when v_patch ? 'bathroom' then coalesce(
        (select array_agg(value) from jsonb_array_elements_text(v_patch->'bathroom') as value),
        '{}'::text[]
      )
      else bathroom
    end,
    alarm = case
      when v_patch ? 'alarm' then coalesce(
        (select array_agg(value) from jsonb_array_elements_text(v_patch->'alarm') as value),
        '{}'::text[]
      )
      else alarm
    end,
    nap_start = case
      when v_patch ? 'nap_start' then nullif(trim(v_patch->>'nap_start'), '')
      else nap_start
    end,
    nap_end = case
      when v_patch ? 'nap_end' then nullif(trim(v_patch->>'nap_end'), '')
      else nap_end
    end,
    waso = case
      when v_patch ? 'waso' then greatest(0, coalesce((v_patch->>'waso')::integer, 0))
      else waso
    end,
    labels = case
      when v_patch ? 'labels' then coalesce(
        (select array_agg(value) from jsonb_array_elements_text(v_patch->'labels') as value),
        '{}'::text[]
      )
      else labels
    end
  where d.user_id = v_user_id and d.sleep_date = v_sleep_date
  returning * into v_draft;

  v_complete :=
    coalesce(nullif(trim(v_draft.bed), ''), '') <> '' and
    coalesce(nullif(trim(v_draft.sleep_start), ''), '') <> '' and
    coalesce(nullif(trim(v_draft.sleep_end), ''), '') <> '';

  if (v_patch ? 'nap_start' or v_patch ? 'nap_end') and exists (
    select 1 from public.sleep_days s
    where s.user_id = v_user_id and s.sleep_date = v_sleep_date
  ) then
    update public.sleep_days s
    set
      nap_start = v_draft.nap_start,
      nap_end = v_draft.nap_end
    where s.user_id = v_user_id and s.sleep_date = v_sleep_date;
  end if;

  if v_complete then
    insert into public.sleep_days (
      user_id,
      sleep_date,
      bed,
      sleep_start,
      sleep_end,
      bathroom,
      alarm,
      nap_start,
      nap_end,
      waso,
      labels
    )
    values (
      v_user_id,
      v_sleep_date,
      v_draft.bed,
      v_draft.sleep_start,
      v_draft.sleep_end,
      coalesce(v_draft.bathroom, '{}'::text[]),
      coalesce(v_draft.alarm, '{}'::text[]),
      v_draft.nap_start,
      v_draft.nap_end,
      coalesce(v_draft.waso, 0),
      coalesce(v_draft.labels, '{}'::text[])
    )
    on conflict on constraint sleep_days_user_id_sleep_date_key do update set
      bed = excluded.bed,
      sleep_start = excluded.sleep_start,
      sleep_end = excluded.sleep_end,
      bathroom = excluded.bathroom,
      alarm = excluded.alarm,
      nap_start = excluded.nap_start,
      nap_end = excluded.nap_end,
      waso = excluded.waso,
      labels = excluded.labels;

    delete from public.sleep_day_drafts d
    where d.user_id = v_user_id and d.sleep_date = v_sleep_date;
  end if;

  return query
    select v_complete as promoted, v_sleep_date as result_sleep_date;
end;
$$ language plpgsql security definer set search_path = public;

grant execute on function public.promote_draft_if_complete(uuid, date, jsonb) to anon, authenticated;
