-- Restore MVP schema (single-user cloud sync)
create table if not exists public.sleep_days (
  id bigint generated by default as identity primary key,
  date_md text not null unique,
  bed text not null,
  sleep_start text not null,
  sleep_end text not null,
  bathroom text[] not null default '{}',
  alarm text[] not null default '{}',
  nap_start text,
  nap_end text,
  waso integer not null default 0 check (waso >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_sleep_days_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_sleep_days_updated_at on public.sleep_days;
create trigger trg_sleep_days_updated_at
before update on public.sleep_days
for each row execute function public.set_sleep_days_updated_at();
